version: '3.8'

services:
  backend:
    build:
      context: ./DotNet8MemberManagement
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
    restart: always
